/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import pack.control.c_koneksi;
import pack.control.controllerToko;
import pack.model.m_toko;

import pack.control.controllerToko;
import pack.model.m_toko;


/**
 *
 * @author user
 */
public class home extends javax.swing.JFrame {
    String nol_jam, nol_menit, nol_detik;
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
        String user = null;
        txtadmin.setText(user);
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hasil = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        kd = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        b2 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        cbpack = new javax.swing.JComboBox<>();
        cbkategori = new javax.swing.JComboBox<>();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        bersih = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        b5 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        Hasil1 = new javax.swing.JLabel();
        cbcari = new javax.swing.JComboBox<>();
        cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtadmin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kd1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Hasil.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        getContentPane().add(Hasil);
        Hasil.setBounds(790, 30, 140, 30);

        tgl.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        getContentPane().add(tgl);
        tgl.setBounds(770, 0, 140, 30);

        kd.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        kd.setText("KASIR :");
        getContentPane().add(kd);
        kd.setBounds(290, 110, 80, 30);

        kode.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        getContentPane().add(kode);
        kode.setBounds(410, 150, 250, 30);

        b2.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b2.setText("Nama Barang");
        getContentPane().add(b2);
        b2.setBounds(270, 200, 130, 30);

        b7.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b7.setText("Kategori Barang");
        getContentPane().add(b7);
        b7.setBounds(270, 250, 130, 30);

        b8.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b8.setText("Jenis Kemasan");
        getContentPane().add(b8);
        b8.setBounds(270, 300, 130, 30);

        harga.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        getContentPane().add(harga);
        harga.setBounds(410, 350, 250, 30);

        nama.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        getContentPane().add(nama);
        nama.setBounds(410, 200, 250, 30);

        cbpack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack", "Dus", "Lusin", "Bijian" }));
        getContentPane().add(cbpack);
        cbpack.setBounds(410, 300, 250, 30);

        cbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Elektronik", "Sandang", "Pecah belah", "Baranglain" }));
        getContentPane().add(cbkategori);
        cbkategori.setBounds(410, 250, 250, 30);

        simpan.setBackground(new java.awt.Color(204, 204, 255));
        simpan.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(710, 150, 110, 30);

        ubah.setBackground(new java.awt.Color(204, 204, 255));
        ubah.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah);
        ubah.setBounds(710, 250, 110, 30);

        keluar.setBackground(new java.awt.Color(204, 204, 255));
        keluar.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(710, 350, 110, 30);

        bersih.setBackground(new java.awt.Color(204, 204, 255));
        bersih.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        bersih.setText("Clear");
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });
        getContentPane().add(bersih);
        bersih.setBounds(710, 200, 110, 30);

        hapus.setBackground(new java.awt.Color(204, 204, 255));
        hapus.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(710, 300, 110, 30);

        b5.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b5.setText("Harga");
        getContentPane().add(b5);
        b5.setBounds(270, 350, 140, 30);

        b9.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b9.setText("Pencarian Berdasarkan Kategori");
        getContentPane().add(b9);
        b9.setBounds(130, 450, 260, 30);

        Hasil1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(Hasil1);
        Hasil1.setBounds(890, 30, 220, 40);

        cbcari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Elektronik", "Sandang", "Pecah belah", "Baranglain" }));
        getContentPane().add(cbcari);
        cbcari.setBounds(390, 450, 230, 30);

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari);
        cari.setBounds(630, 450, 110, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Packaging", "Harga"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 490, 910, 200);

        txtadmin.setFont(new java.awt.Font("DFGothic-EB", 0, 18)); // NOI18N
        getContentPane().add(txtadmin);
        txtadmin.setBounds(400, 110, 140, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 440, 930, 260);

        kd1.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        kd1.setText("Kode Barang");
        getContentPane().add(kd1);
        kd1.setBounds(270, 150, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 26)); // NOI18N
        jLabel5.setText("SUPERMARKET CETAR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 20, 230, 30);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel8.setText("Jl. SAWOJAJAR GANG 13 NO. 60, SAWOJAJAR, MALANG.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 50, 610, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Email : bayu_krisna_24rpl@student.smktelkom-mlg.sch.id");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 80, 450, 20);

        jLabel4.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 18)); // NOI18N
        jLabel4.setText("DATA BARANG TERSEDIA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 400, 260, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 440);

        setBounds(0, 0, 944, 738);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
       ctoko.SimpanData();
       ctoko.isiTable();
         
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
     ctoko.Ubah();
     ctoko.isiTable();
      
    }//GEN-LAST:event_ubahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       dispose(); 
    }//GEN-LAST:event_keluarActionPerformed

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
      ctoko.Reset();
    }//GEN-LAST:event_bersihActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       ctoko.Hapus();
       ctoko.isiTable();
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
      ctoko.CariKategori();
      //ctoko.isiTable();
    }//GEN-LAST:event_cariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String user1 = login.user;
        txtadmin.setText(user1);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int baris = table.getSelectedRow();
        if(baris != -1){
            kode.setText(table.getValueAt(baris, 0).toString());
            nama.setText((String) table.getValueAt(baris, 1));
            cbkategori.setSelectedItem(table.getValueAt(baris, 2).toString());
            cbpack.setSelectedItem(table.getValueAt(baris, 3).toString());
            harga.setText(table.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    
    
    public JTextField getTxtKode(){
 return kode;
 }
 public JTextField getTxtNama(){
 return nama;
 }
 public JTextField getTxtHarga(){
 return harga;
 }
 public JComboBox getCbKategori(){
 return cbkategori;
 }
 public JComboBox getCbJenis(){
 return cbpack;
 }
 public JComboBox getCbCariKategori(){
 return cbcari;
 }
 public JButton getButtonHapus(){
 return hapus;
 }

 public JButton getButtonBersih(){
 return  bersih;
 }
 public JButton getButtonSimpan(){
 return simpan;
 }
 public JButton getButtonUbah(){
 return ubah;
 }
 public JButton getButtonKeluar(){
 return keluar;
 }
 public JTable getTableData(){
 return table;
 }
 public void setTanggal() {
       java.util.Date skrg = new java.util.Date();
       java.text.SimpleDateFormat kal = new
       java.text.SimpleDateFormat("dd/MM/yyyy");
       tgl.setText(kal.format(skrg));
    }
    
    
    
    public void setJam() {
       ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
                
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if (nilai_jam<=9){
                    nol_jam = "0";
                } if (nilai_menit <= 9) {
                    nol_menit = "0";
                } if (nilai_detik <= 9){
                    nol_detik = "0";
                }
               
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Hasil.setText(jam+":"+menit+":"+detik);
            }
        };
    new Timer(100, taskPerformer).start();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil;
    private javax.swing.JLabel Hasil1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JButton bersih;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cbcari;
    private javax.swing.JComboBox<String> cbkategori;
    private javax.swing.JComboBox<String> cbpack;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kd;
    private javax.swing.JLabel kd1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField nama;
    private javax.swing.JButton simpan;
    private javax.swing.JTable table;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel txtadmin;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
